<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3 (Python 3.13.7 on win32)" generated="2025-09-08T16:15:25.907828" rpa="false" schemaversion="5">
<suite id="s1" name="RobotFramework" source="C:\Users\parag_bansal\PycharmProjects\RobotFramework">
<suite id="s1-s1" name="Tests" source="C:\Users\parag_bansal\PycharmProjects\RobotFramework\Tests">
<suite id="s1-s1-s1" name="Test Connectivity" source="C:\Users\parag_bansal\PycharmProjects\RobotFramework\Tests\test_connectivity.robot">
<test id="s1-s1-s1-t1" name="Test AWS Connection" line="9">
<kw name="Verify AWS Connection" owner="MyCustomLibrary">
<msg time="2025-09-08T16:15:26.240270" level="INFO">Found credentials in shared credentials file: ~/.aws/credentials</msg>
<doc>Robot Framework keyword for verifying AWS connection.</doc>
<status status="PASS" start="2025-09-08T16:15:26.137139" elapsed="0.925501"/>
</kw>
<status status="PASS" start="2025-09-08T16:15:26.135616" elapsed="0.927734"/>
</test>
<status status="PASS" start="2025-09-08T16:15:25.948564" elapsed="1.116162"/>
</suite>
<status status="PASS" start="2025-09-08T16:15:25.947222" elapsed="1.118949"/>
</suite>
<status status="PASS" start="2025-09-08T16:15:25.911747" elapsed="1.155617"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="RobotFramework" id="s1" pass="1" fail="0" skip="0">RobotFramework</stat>
<stat name="Tests" id="s1-s1" pass="1" fail="0" skip="0">RobotFramework.Tests</stat>
<stat name="Test Connectivity" id="s1-s1-s1" pass="1" fail="0" skip="0">RobotFramework.Tests.Test Connectivity</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
